### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by TOLIE-OFFICIAL** [easyteacher/plasma-wallpapers-xml#9]
would you like to hava a brief introduce about how to use the plugin in the README file? thx

**Comment by TobiPeterG** [comment]
Hey, just follow these instructions: https://www.debugpoint.com/2022/04/custom-light-dark-wallpaper-gnome/

Just remember to rename the xml and remove the .in postfix :)

**Comment by TOLIE-OFFICIAL** [comment]
> Hey, just follow these instructions: https://www.debugpoint.com/2022/04/custom-light-dark-wallpaper-gnome/
> 
> Just remember to rename the xml and remove the .in postfix :)

thx,I will try it. Have a good day!
